### PR TITLE
Fix 177

### PR DESCRIPTION
**Pull request by Lokathor**
Closes https://github.com/Lokathor/bytemuck/issues/177

### CODE REVIEW

**Review by MarijnS95 — APPROVED** [review]
Yup thanks, that is exactly what I was looking for!

I thought I saw the same constraint on other functions, but would have to recheck if/where, and if they may be intended.

**Comment by Lokathor** [comment]
If you find more cases feel free to open more issues, but i'll merge and publish this update for now.

**Comment by MarijnS95** [comment]
That's most appreciated, while I'm migrating to `bytemuck` :)

**Comment by Lokathor** [comment]
released `bytemuck-1.13.1`. As I write this it's on crates.io, but it'll be ages before docs.rs shows the new docs (252 in queue, so like a 12 hour wait just if every run takes only 3 minutes each, docs.rs has been clogged as heck lately)

**Comment by MarijnS95** [comment]
Yup, thanks! Already using it, and already don't need it after switching to `cast_slice().to_vec()` as discussed to likely be simpler and more performant :)

**Pull request merged**
