### PR TITLE
hide `unexpected_cfgs` warnings in proc-macro generated code

### LINKED ISSUE #286: Future `unexpected_cfgs` warning from `derive(CheckedBitPattern)`
Use Rust nightly or beta (1.84.0-beta.1), `bytemuck` 1.20.0, and compile this trivial program:

```rust
#[derive(Clone, Copy, bytemuck::CheckedBitPattern)]
#[repr(C)]
struct Foo {}
```

to receive this warning:

```rust
warning: unexpected `cfg` condition value: `spirv`
 --> src/lib.rs:1:23
  |
1 | #[derive(Clone, Copy, bytemuck::CheckedBitPattern)]
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: expected values for `target_arch` are: `aarch64`, `arm`, `arm64ec`, `avr`, `bpf`, `csky`, `hexagon`, `loongarch64`, `m68k`, `mips`, `mips32r6`, `mips64`, `mips64r6`, `msp430`, `nvptx64`, `powerpc`, `powerpc64`, `riscv32`, `riscv64`, `s390x`, `sparc`, `sparc64`, `wasm32`, `wasm64`, `x86`, `x86_64`, and `xtensa`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
  = note: this warning originates in the derive macro `bytemuck::CheckedBitPattern` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by Freax13**
Closes #286

### CODE REVIEW

**Review by fu5ha — APPROVED** [review]
Looks like a nice solution to me

**Comment by Lokathor** [comment]
released in bytemuck_derive-1.8.1

**Comment by Lokathor** [comment]
Could you open that as a new issue? It's very important, but It's hard to keep track of an old and already-merged PR.

**Comment by stegaBOB** [comment]
I just opened a PR since it was a quick fix here: https://github.com/Lokathor/bytemuck/pull/305. But it actually looks like someone already did it a few months ago :sweat_smile:  https://github.com/Lokathor/bytemuck/pull/291

**Comment by Freax13** [comment]
> I just opened a PR since it was a quick fix here: #305. But it actually looks like someone already did it a few months ago 😅 #291

image

**Pull request merged**
